- action:
  - data:
      brightness: 255
      entity_id: light.osram_lightify_br_rgbw_00a5c1f9_3
      rgb_color:
      - 255
      - 0
      - 0
    service: light.turn_on
  - data:
      message: '@nutella say MASTER BUILD {{ states(''sensor.nutshell_master_raw_status'')
        }}'
      target:
      - '#bots'
    service: notify.notify
  alias: Build Failed
  condition: []
  id: '1513112347676'
  trigger:
  - entity_id: binary_sensor.nutshell_master
    platform: state
    to: 'on'
- action:
  - data:
      brightness: 255
      color_temp: 370
      entity_id: light.osram_lightify_br_rgbw_00a5c1f9_3
    service: light.turn_on
  alias: Build Restored
  condition: []
  id: '1513112391167'
  trigger:
  - entity_id: binary_sensor.nutshell_master
    platform: state
    to: 'off'
- action:
  - data:
      message: '{{ [''Hot coffee on the way! :coffee:'',''Coffee brewing! :highfive:'',''Coffee
        time! :excited:'','':coffee_parrot::coffee_parrot::coffee_parrot::coffee_parrot:'']
        | random }}'
      target:
      - '#coffee'
    service: notify.notify
  - data:
      entity_id: input_boolean.coffee_brewed_today
    service: input_boolean.turn_on
  alias: Coffee Brewing
  condition: []
  id: '1513374990227'
  trigger:
  - entity_id: binary_sensor.coffee_brewing
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: input_boolean.coffee_brewed_today
    service: input_boolean.turn_off
  alias: Reset Coffee Brewed Today Status
  condition:
  - condition: state
    entity_id: input_boolean.coffee_brewed_today
    state: 'on'
  id: '1513375490034'
  trigger:
  - at: 00:00:00
    platform: time
