- id: '1513112347676'
  alias: Build failed
  trigger:
  - entity_id: binary_sensor.nutshell_master
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: '@nutella say MASTER BUILD {{ states(''sensor.nutshell_master_raw_status'')
        }}'
      target:
      - '#bots'
    service: notify.slack_nutshell
- id: '1513374990227'
  alias: Coffee brewed
  trigger:
  - entity_id: binary_sensor.coffee_brewing
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: input_boolean.coffee_brewed_today
    service: input_boolean.turn_on
  - delay: 00:01:30
  - data:
      message: '{{ [''Hot coffee is ready! :coffee:'',''Coffee brewed! :highfive:'',''Coffee
        time! :excited:'','':coffee_parrot::coffee_parrot::coffee_parrot::coffee_parrot:'',''Coffee
        ready to go!'',''Thanks for making coffee! :heart:''] | random }}'
      target:
      - '#coffee'
    service: notify.slack_nutshell
- id: '1513375490034'
  alias: Reset coffee brewed today status
  trigger:
  - at: 00:00:00
    platform: time
  condition:
  - condition: state
    entity_id: input_boolean.coffee_brewed_today
    state: 'on'
  action:
  - data:
      entity_id: input_boolean.coffee_brewed_today
    service: input_boolean.turn_off
- id: '1582056936886'
  alias: Build light
  description: ''
  trigger:
  - entity_id: sensor.build_light_color
    platform: state
  - minutes: '30'
    platform: time_pattern
  condition: []
  action:
  - service: script.update_build_light_color
